// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuhbPhiGcp9UKDHMkfcJ3ODfLJCyuUaTQ',
    appId: '1:219212776814:web:2d31b8f6eba7fff9e72d7f',
    messagingSenderId: '219212776814',
    projectId: 'khosach-f525d',
    authDomain: 'khosach-f525d.firebaseapp.com',
    storageBucket: 'khosach-f525d.firebasestorage.app',
    measurementId: 'G-21135SCWKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6yW_a7YLnSZzPC6lQiG5QRqPJmX1yRjk',
    appId: '1:219212776814:android:c1f6301e9cb7dfffe72d7f',
    messagingSenderId: '219212776814',
    projectId: 'khosach-f525d',
    storageBucket: 'khosach-f525d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpwvSp1wkMlOItvcdgFWNwY92Gm4cNM4k',
    appId: '1:219212776814:ios:e15fd0cb2bdf9996e72d7f',
    messagingSenderId: '219212776814',
    projectId: 'khosach-f525d',
    storageBucket: 'khosach-f525d.firebasestorage.app',
    iosBundleId: 'com.example.shopbansach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpwvSp1wkMlOItvcdgFWNwY92Gm4cNM4k',
    appId: '1:219212776814:ios:e15fd0cb2bdf9996e72d7f',
    messagingSenderId: '219212776814',
    projectId: 'khosach-f525d',
    storageBucket: 'khosach-f525d.firebasestorage.app',
    iosBundleId: 'com.example.shopbansach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuhbPhiGcp9UKDHMkfcJ3ODfLJCyuUaTQ',
    appId: '1:219212776814:web:6b2d149914449dd2e72d7f',
    messagingSenderId: '219212776814',
    projectId: 'khosach-f525d',
    authDomain: 'khosach-f525d.firebaseapp.com',
    storageBucket: 'khosach-f525d.firebasestorage.app',
    measurementId: 'G-0VN9LSM100',
  );
}
